name: Build, Run, and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Build and run C# project
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # adjust to your .NET version

    - name: Build C# project
      run: dotnet build ./backend/backend.sln

    - name: Run C# project tests
      run: dotnet test ./backend/backend.sln

    # Install Node.js and run Playwright tests
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '9.8.1'  # adjust to your Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: ./backend/test

    - name: Run Playwright tests
      run: npm test
      working-directory: ./backend/test
